"""empty message

Revision ID: 3a31d6cdc439
Revises: 
Create Date: 2020-05-04 23:00:49.398767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a31d6cdc439'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('lastname', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('avatar', sa.String(length=256), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('comments',
    sa.Column('cm_sender', sa.String(length=64), nullable=False),
    sa.Column('cm_recipient', sa.String(length=64), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('comment_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cm_recipient'], ['users.username'], ),
    sa.ForeignKeyConstraint(['cm_sender'], ['users.username'], ),
    sa.PrimaryKeyConstraint('cm_sender', 'comment_date')
    )
    op.create_table('direct_messages',
    sa.Column('sender_username', sa.String(length=64), nullable=False),
    sa.Column('recipient_username', sa.String(length=64), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('sending_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_username'], ['users.username'], ),
    sa.ForeignKeyConstraint(['sender_username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('sender_username', 'recipient_username', 'sending_date')
    )
    op.create_table('follows',
    sa.Column('follower_username', sa.String(length=64), nullable=False),
    sa.Column('following_username', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['follower_username'], ['users.username'], ),
    sa.ForeignKeyConstraint(['following_username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('follower_username', 'following_username')
    )
    op.create_table('likes',
    sa.Column('like_sender', sa.String(length=64), nullable=False),
    sa.Column('like_recipient', sa.String(length=64), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.Column('like_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['like_recipient'], ['users.username'], ),
    sa.ForeignKeyConstraint(['like_sender'], ['users.username'], ),
    sa.PrimaryKeyConstraint('like_sender', 'like_date')
    )
    op.create_table('posts',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('picture', sa.String(length=256), nullable=False),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('username', 'post_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('likes')
    op.drop_table('follows')
    op.drop_table('direct_messages')
    op.drop_table('comments')
    op.drop_table('users')
    # ### end Alembic commands ###
